### ISSUE TITLE
B站视频解析错误

### ISSUE THREAD

**Issue by Yql66** [SK-415/bilireq#7]
![image](https://user-images.githubusercontent.com/111969738/190568081-ef04db2c-9a9d-4408-8c0b-73f770687814.png)

**Comment by SK-415** [comment]
请更新 bilireq 至最新版（v0.2.2）

**Comment by SK-415** [comment]
已经向真寻提交 PR 修复了。

想要临时解决的话可以删除 `poetry.lock` 重新执行 `poetry install`。
